import os
import json
import re
from tqdm import tqdm
from openai import OpenAI
import time
Evalutor = OpenAI(
      api_key=""
  )
evaluation_prompt = """
You are a biomedical expert and a strict reviewer for reasoning chain evaluation.

You will be provided with two fields:
- **input**: This is the *original task*, including all instructions, the target sentence, reference context, and any other information originally given to the language model for relation extraction. You do NOT need to solve the original task; it is just background.
- **think**: This is the *reasoning chain* generated by a model as an attempt to complete the original task.

Your ONLY job is to evaluate the **quality of the reasoning chain** (“think”), strictly according to the following eight criteria, and return a JSON with your scores and a brief comment.

**Evaluation Criteria (score each from 1 to 5):**
1. **Medical Soundness**: Is the reasoning medically accurate, without factual mistakes or violations of biomedical knowledge?
2. **Semantic Alignment**: Semantic Alignment: Does the reasoning strictly adhere to and reflect the semantic content of the input (target sentence and context), without introducing any distortion or information not present in the original text?
3. **Reasoning Accuracy**: Does the reasoning process logically arrive at conclusions whose meaning is substantially consistent with the gold standard answer in the input? The output format does not need to be identical—as long as the semantic intent and relations match, it should be considered correct. (If the meaning contradicts the gold standard, assign 0.)
4. **Naturalness of Reasoning Origin**: Is the reasoning presented as if it was independently and objectively derived, with no explicit or implicit references to the existence of a gold standard answer? Any hint of comparison or reference to the gold answer, or signs the model knew the correct answer, assign 0. Please be strict about this.
5. **Reasoning Length**: Is the reasoning concise (ideally 200-300 words)? If the word count is above 400 or below 200, score 0.
6. **Linguistic Fluency**: Is the reasoning chain written in smooth, natural, and well-structured language?
7. **Repetition-Free**: Does the reasoning avoid unnecessary repetition or redundancy?
8. **Logical Coherence**: Are all statements in the reasoning mutually consistent, with no internal contradictions or logical breaks?

Return your evaluation in **only** the following JSON format:
{
"score_medical": int,
"score_semantic": int,
"score_accuracy": int,
"score_naturalness": int,
"score_length": int,
"score_fluency": int,
"score_repetition": int,
"score_coherence": int,
"comment": "Short summary comment"
}

"""


def safe_extract_json(text):
    try:
        return json.loads(text)
    except:
        match = re.search(r"\{[\s\S]*?\}", text)
        if match:
            try:
                return json.loads(match.group(0))
            except Exception as e:
                print("JSON parse error:", e)
        return None

def call_openai_evaluator(input_text, answer, think_chain):
    eval_input = f"""{evaluation_prompt}\n\ninput: {input_text}\nthink: {think_chain}\nGround Truth Answer: {answer}"""

    response = Evalutor.chat.completions.create(
        model="gpt-4o",
        messages=[{'role': 'user', 'content': eval_input}],
        temperature=0.0
    )
    raw_output = response.choices[0].message.content
    eval_json = safe_extract_json(raw_output)
    if not eval_json:
        eval_json = {
            "score_medical": 0,
            "score_semantic": 0,
            "score_accuracy": 0,
            "score_naturalness": 0,
            "score_length": 0,
            "score_fluency": 0,
            "score_repetition": 0,
            "score_coherence": 0,
            "comment": "Model parsing failed"
        }
    return eval_json


input_path = "the_reasoning.jsonl"
output_path = "the_score.jsonl"
stat_path = "the_erroe_number.json"



low_score_counter = {
    "score_medical": 0,
    "score_semantic": 0,
    "score_accuracy": 0,
    "score_naturalness": 0,
    "score_length": 0,
    "score_fluency": 0,
    "score_repetition": 0,
    "score_coherence": 0,
}

score_sum = {
    "score_medical": 0,
    "score_semantic": 0,
    "score_accuracy": 0,
    "score_naturalness": 0,
    "score_length": 0,
    "score_fluency": 0,
    "score_repetition": 0,
    "score_coherence": 0,
}
total_count = 0
all_outputs = []

with open(input_path, 'r') as f:
    lines = f.readlines()

for idx, line in enumerate(tqdm(lines)):
    item = json.loads(line)
    input_text = item['input']
    true_answer = item['true_answer']
    think_chain = item['think']

    score = call_openai_evaluator(input_text, true_answer, think_chain)
    output_item = {
        "input": input_text,
        "true_answer": true_answer,
        "think": think_chain,
        **score
    }
    all_outputs.append(output_item)
    total_count += 1
    for k in low_score_counter:
        v = score.get(k, 0)
        if v < 4:
            low_score_counter[k] += 1
        score_sum[k] += v
    with open(output_path, 'a', encoding='utf-8') as fw:
        fw.write(json.dumps(output_item, ensure_ascii=False) + '\n')
    time.sleep(0.2) 

score_avg = {k: (score_sum[k] / total_count if total_count else 0) for k in score_sum}

final_stat = {
    "count_below_4": low_score_counter,
    "mean_score": score_avg,
    "total": total_count
}

with open(stat_path, 'w', encoding='utf-8') as fw:
    json.dump(final_stat, fw, indent=2, ensure_ascii=False)

